const MOCK_CARDS = [
  {
    region: "china",
    topic: "social",
    strategic_vertical: "gold_jewellery",
    canonical_event_key: "east_asia_young_gold_gifting_2026_q2",
    primary_source_id: "raw_cn_001",
    supporting_source_ids: ["raw_cn_002", "raw_cn_003"],
    source_count: 3,
    importance_score: 0.6,
    confidence_score: 0.78,
    title: "中国年轻消费者推动小克重金饰礼赠增长",
    summary: "社交平台上小克重、可叠戴和寓意型金饰内容传播增强，年轻消费者把金饰作为节日礼赠和自我奖励选择。",
    source_url: "https://example.com/china-young-gold",
  },
  {
    region: "japan",
    topic: "product",
    strategic_vertical: "lab_grown_diamond",
    canonical_event_key: "east_asia_lab_diamond_price_band_2026_q2",
    primary_source_id: "raw_jp_001",
    supporting_source_ids: ["raw_jp_002"],
    source_count: 2,
    importance_score: 0.6,
    confidence_score: 0.66,
    title: "日本零售商测试更低价格带实验室钻石系列",
    summary: "日本珠宝零售商用更轻量的设计和明确价格带吸引年轻订婚和礼物场景，实验室钻石成为预算友好卖点。",
    source_url: "https://example.com/japan-lab-diamond",
  },
  {
    region: "southeast_asia",
    topic: "social",
    strategic_vertical: "overseas_retail_channels",
    canonical_event_key: "sea_livestream_jewellery_2026_q2",
    primary_source_id: "raw_sea_001",
    supporting_source_ids: ["raw_sea_002"],
    source_count: 2,
    importance_score: 0.6,
    confidence_score: 0.7,
    title: "东南亚直播电商珠宝类目升温",
    summary: "区域电商平台珠宝直播间增长明显，轻金饰、转运珠和节日礼赠款成为年轻消费者高频互动品类。",
    source_url: "https://example.com/sea-live-jewellery",
  },
  {
    region: "us",
    topic: "competition",
    strategic_vertical: "lab_grown_diamond",
    canonical_event_key: "north_america_lab_diamond_price_drop_2026_q2",
    primary_source_id: "raw_us_001",
    supporting_source_ids: ["raw_us_002", "raw_us_003", "raw_us_004"],
    source_count: 4,
    importance_score: 0.6,
    confidence_score: 0.84,
    title: "美国实验室钻石零售价继续下探",
    summary: "美国多个线上珠宝平台下调实验室钻石定价，并将预算友好、设计更新快作为年轻客群的核心卖点。",
    source_url: "https://example.com/us-lab-diamond-price",
  },
  {
    region: "canada",
    topic: "product",
    strategic_vertical: "gold_jewellery",
    canonical_event_key: "north_america_recycled_gold_claims_2026_q2",
    primary_source_id: "raw_ca_001",
    supporting_source_ids: ["raw_ca_002"],
    source_count: 2,
    importance_score: 0.6,
    confidence_score: 0.68,
    title: "加拿大精品渠道提高再生金材料说明要求",
    summary: "渠道买手要求供应商展示再生金比例和来源追溯说明，ESG 材料标签开始影响新品准入和货架推荐。",
    source_url: "https://example.com/canada-recycled-gold",
  },
  {
    region: "australia",
    topic: "product",
    strategic_vertical: "gold_jewellery",
    canonical_event_key: "oceania_gold_volatility_retail_2026_q2",
    primary_source_id: "raw_au_001",
    supporting_source_ids: ["raw_au_002"],
    source_count: 2,
    importance_score: 0.6,
    confidence_score: 0.69,
    title: "澳大利亚渠道增加 ESG 再生金饰系列",
    summary: "澳大利亚零售商在年轻客群礼赠场景中增加再生金与可追溯材料标签，同时用更清晰的价格带降低金价波动影响。",
    source_url: "https://example.com/australia-gold-volatility",
  },
  {
    region: "singapore",
    topic: "supply",
    strategic_vertical: "gold_jewellery",
    canonical_event_key: "sea_traceability_supplier_check_2026_q2",
    primary_source_id: "raw_sg_001",
    supporting_source_ids: ["raw_sg_002"],
    source_count: 2,
    importance_score: 0.6,
    confidence_score: 0.72,
    title: "新加坡渠道要求供应商补充贵金属来源追溯文件",
    summary: "本地渠道开始要求贵金属供应商提交更完整的来源和加工链路说明，可能影响区域供货节奏。",
    source_url: "https://example.com/singapore-traceability",
  },
  {
    region: "uk",
    topic: "watch",
    strategic_vertical: "watches",
    canonical_event_key: "uk_watch_collectors_2026_q2",
    primary_source_id: "raw_uk_001",
    supporting_source_ids: [],
    source_count: 1,
    importance_score: 0.35,
    confidence_score: 0.4,
    title: "英国复古腕表社区讨论升温",
    summary: "复古腕表收藏社区讨论热度提升，但与当前年轻消费、ESG、实验室钻石战略关联有限。",
    source_url: "https://example.com/uk-watch",
  },
];

const MOCK_MANUAL_PUSHES = [
  { insight_id: "B:lab_grown_diamond:north_america_lab_diamond_price_drop_2026_q2", actor_tag: "B1_market", action: "push" },
  { insight_id: "B:lab_grown_diamond:north_america_lab_diamond_price_drop_2026_q2", actor_tag: "B2_product", action: "push" },
  { insight_id: "C:north_america:north_america_lab_diamond_price_drop_2026_q2", actor_tag: "C3_north_america", action: "push" },
  { insight_id: "C:east_asia:east_asia_lab_diamond_price_band_2026_q2", actor_tag: "C1_east_asia", action: "push" },
];

module.exports = {
  MOCK_CARDS,
  MOCK_MANUAL_PUSHES,
};
